version: '3.8'

services:
  servicea:
    container_name: servicea
    build:
      context: ./
      dockerfile: ./DockerfileA
    ports:
      - 3001:80
  serviceb:
    container_name: serviceb
    build:
      context: ./
      dockerfile: ./DockerfileB
    ports:
      - 3002:80
  traefix:
    image: traefik:v2.7
    ports:
      - 8888:8888
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./provider.yaml:/etc/traefik/provider.yaml
